module.exports = {
	List:[
	{"measure":"Bag", "code":"BG"},
	{"measure":"Barrel", "code":"BA"},
	{"measure":"Bolt", "code":"BT"},
	{"measure":"Box", "code":"BOX"},
	{"measure":"Bunch", "code":"BH"},
	{"measure":"Bundle", "code":"BE"},
	{"measure":"Butt", "code":"BU"},
	{"measure":"Canister", "code":"CI"},
	{"measure":"Carton", "code":"CT"},
	{"measure":"Case", "code":"CS"},
	{"measure":"Centimeter", "code":"CM"},
	{"measure":"Container", "code":"CON"},
	{"measure":"Crate", "code":"CR"},
	{"measure":"Cylinder", "code":"CY"},
	{"measure":"Dozen", "code":"DOZ"},
	{"measure":"Foot", "code":"FT"},
	{"measure":"Kilogram", "code":"KG"},
	{"measure":"Kilograms", "code":"KGS"},
	{"measure":"Liter", "code":"L"},
	{"measure":"Meter", "code":"M"},
	{"measure":"Pakage", "code":"PK"},
	{"measure":"Packet", "code":"PA"},
	{"measure":"Pair", "code":"PAR"},
	{"measure":"Pairs", "code":"PRS"},
	{"measure":"Pallet", "code":"PAL"},
	{"measure":"Piece", "code":"PC"},
	{"measure":"Pieces", "code":"PCS"},
	{"measure":"Pound", "code":"LB"},
	{"measure":"Proof Liter", "code":"PF"},
	{"measure":"Roll", "code":"ROL"},
	{"measure":"Set", "code":"SET"},
	{"measure":"Square Meter", "code":"SME"},
	{"measure":"Square Yard ", "code":"SYD"},
	{"measure":"Tube", "code":"TU"},
	{"measure":"Yard ", "code":"YD"}
]
}